# Site settings
title: "newworld"
email: antiless@163.com
description: "Write my mind here."
baseurl: "/noeast/"
url: "http://auv1107.github.io/noeast.github.com/"
title_description: ""
title_image: "https://d13yacurqjgara.cloudfront.net/users/29248/screenshots/2218271/dribbble_1x.jpg"
#google_analytics: "UA-20365477-4"
#disqus_account: cartenoire
github_repository: https://github.com/auv1107/
#addthis_id: ra-513c6fa83da6ec67
post_limit: 5

# Social usernames/URLs
#twitter_username: 
github_username: auv1107
#linkedin_link: http://carte-noire.jacobtomlinson.co.uk/
#google_plus_link: http://carte-noire.jacobtomlinson.co.uk/
#stackoverflow_link: http://carte-noire.jacobtomlinson.co.uk/

# Footer
footer_left: "Made with <i class=\"fa fa-heart\"></i> by <a href=\"https://twitter.com/APrilFooooolish\">Antiless</a>"
footer_right: "&lt;/&gt; on <a href=\"https://github.com/jacobtomlinson/auv1107\">Github</a> &nbsp;<i class=\"fa fa-github-alt\"></i>"

# Build settings
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript"]
permalink: pretty
exclude: [vendor]
